import {mkdir, writeFile} from 'node:fs/promises'
import {normalize} from '../src/game/wordlist.ts'

const BASE = 'https://raw.githubusercontent.com/jacksun007/codenames/HEAD'
const OUT = new URL('../src/data/wordlists/', import.meta.url)

const PACKS = [
  {id: 'original', file: 'vanilla', name: 'Original', note: 'The base game deck'},
  {id: 'duet', file: 'duet', name: 'Duet', note: 'Overlaps Original substantially'},
  {id: 'everything', file: 'codenames', name: 'Everything', note: 'Union of the licensed decks, deduped'},
  {id: 'undercover', file: 'undercover', name: 'Deep Undercover', note: 'Adult; off by default'},
  {id: 'disney', file: 'disney', name: 'Disney', note: 'Themed'},
  {id: 'potter', file: 'potter', name: 'Harry Potter', note: 'Themed'},
  {id: 'simpsons', file: 'simpsons', name: 'Simpsons', note: 'Themed'},
  {id: 'mtg', file: 'mtg', name: 'Magic: The Gathering', note: 'Themed'}
]

await mkdir(OUT, {recursive: true})

const rows: string[] = []
const manifest: Array<{id: string; name: string; count: number; note: string}> = []

for (const pack of PACKS) {
  const res = await fetch(`${BASE}/${pack.file}.txt`)
  if (!res.ok) throw new Error(`${pack.file}: ${res.status}`)
  const words = normalize((await res.text()).split(/\r?\n/))
  await writeFile(new URL(`${pack.id}.json`, OUT), `${JSON.stringify(words)}\n`)
  rows.push(`| ${pack.name} | \`${pack.id}.json\` | ${words.length} | ${pack.file}.txt | ${pack.note} |`)
  manifest.push({id: pack.id, name: pack.name, count: words.length, note: pack.note})
  console.log(`${pack.id.padEnd(12)} ${words.length}`)
}

await writeFile(new URL('manifest.json', OUT), `${JSON.stringify(manifest, null, 2)}\n`)

await writeFile(
  new URL('SOURCES.md', OUT),
  `# Word list sources

Generated by \`scripts/build-wordlists.ts\`. Do not hand-edit the JSON; rerun the
script instead. Regenerating is a deliberate act and is not part of \`npm run build\`.

Every pack is normalized identically: drop blanks and \`#\` comments, strip leading
\`=\` and \`-\` markers, collapse whitespace, uppercase, dedupe case-insensitively
keeping the first occurrence, sort.

| Pack | File | Words | Source file | Notes |
|---|---|---|---|---|
${rows.join('\n')}

Fetched from [jacksun007/codenames](${BASE.replace('/raw.githubusercontent.com', '/github.com').replace('/HEAD', '')}),
which carries the widest spread of expansions and themed decks in one place.

Cross-checked against:

- [sagelga/codenames](https://github.com/sagelga/codenames) — multi-language, the
  source if non-English packs are ever added
- [Filodoxia/codenames-wordlists](https://github.com/Filodoxia/codenames-wordlists)
  — the horsepaste.com lists

## Licensing

Neither source carries a licence file. Individual words are not copyrightable,
but a curated deck is arguably a compilation, and the themed packs lean on
trademarks. This is the normal risk people take for a private game among
friends; it is recorded here so it is known rather than discovered.
`
)

console.log('SOURCES.md written')
